version: '3'

services:
  alfresco:
    image: ${DOCKER_IMAGE}
    ports:
    - ${COMPOSE_ALFRESCO_TCP_8080:-8080}
#    - 8000:8000 # DEBUG
    environment:
#    - DEBUG=true
    - DB_URL=jdbc:postgresql://postgresql:5432/alfresco
    - DB_DRIVER=org.postgresql.Driver
    - ALFRESCO_PROTOCOL=http
    - GLOBAL_index.subsystem.name=noindex
    - GLOBAL_ooo.enabled=false
    - GLOBAL_jodconverter.enabled=false
#    - JMX_ENABLED=true
    - JAVA_OPTS_PERM_GEN=-XX:PermSize=512m -XX:MaxPermSize=512m
    - GLOBAL_messaging.broker.url=nio://activemq:61616
    - GLOBAL_contentPropertyRestrictions.enabled=false
    volumes:
      - alfresco:/opt/alfresco/alf_data
  postgresql:
    image: docker.io/xenit/postgres:13
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=alfresco
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=alfresco
  activemq:
    image: alfresco/alfresco-activemq:5.16.1


volumes:
  alfresco:
  postgres:
